const action_types = {
    GET_HOME: "GET_HOME",
    SET_CURRENT_SONG_ID: "SET_CURRENT_SONG_ID",
    PLAY: "PLAY",
    AT_PLAYLIST: "AT_PLAYLIST",
    PLAYLIST: "PLAYLIST",
    SHOW_SIDEBAR_RIGHT: "SHOW_SIDEBAR_RIGHT",
    SET_CURRENT_SONG_DATA: "SET_CURRENT_SONG_DATA",
    SET_CURRENT_PLAYLIST_NAME: "SET_CURRENT_PLAYLIST_NAME",
    ADD_RECENT_SONG: "ADD_RECENT_SONG",
    SEARCH: "SEARCH",
    SEARCH_SONGS: "SEARCH_SONGS",
    IS_SCROLL_TOP: "IS_SCROLL_TOP",
    WEEK_CHART_LINK: "WEEK_CHART_LINK"
}

export default action_types